// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr8H9If4nOkCNB41zRu6mLHOfr3NVQHoI',
    appId: '1:334444253343:android:a8e01774d2fb82d60192aa',
    messagingSenderId: '334444253343',
    projectId: 'book-list-page-535f4',
    storageBucket: 'book-list-page-535f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqJrrT5-WStZu8SJuBZHn4i4AqXYM8m-8',
    appId: '1:334444253343:ios:82e017bcc6d080270192aa',
    messagingSenderId: '334444253343',
    projectId: 'book-list-page-535f4',
    storageBucket: 'book-list-page-535f4.appspot.com',
    iosClientId: '334444253343-0mo0ck2sdigq9kc56sd8e65iovu1chr3.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookListSample',
  );
}
